/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
Author: ffish.asia / floraZia.com (https://sketchfab.com/ffishAsia-and-floraZia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/deep-autumn-5k-followers-milestone-0d4dac6d670c46a38154bcc205cb9094
Title: 🍂 Deep Autumn 🍁 5K Followers Milestone
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-8.133, 11.637, -1.885]} rotation={[-1.589, 0.27, 3.124]} scale={1.573}>
        <mesh geometry={nodes.Object_6.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.material_0} />
      </group>
      <group position={[-7.818, -3.581, -16.822]} rotation={[-0.389, -0.096, 2.123]} scale={1.205}>
        <mesh geometry={nodes.Object_9.geometry} material={materials['material_0.001']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['material_0.001']} />
      </group>
      <group position={[1.27, 9.82, -8.117]} rotation={[2.602, 1.337, 1.612]} scale={1.012}>
        <mesh geometry={nodes.Object_12.geometry} material={materials['material_0.002']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['material_0.002']} />
      </group>
      <group position={[-6.55, -6.448, 7.996]} rotation={[-2.11, 0.49, -2.675]} scale={1.097}>
        <mesh geometry={nodes.Object_15.geometry} material={materials['material_0.003']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['material_0.003']} />
      </group>
      <group position={[11.118, -7.316, -4.253]} rotation={[-0.5, -0.974, 1.375]} scale={1.285}>
        <mesh geometry={nodes.Object_18.geometry} material={materials['material_0.004']} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['material_0.004']} />
      </group>
      <group position={[-18.589, -4.677, -7.032]} rotation={[0.953, -0.088, 0.822]} scale={0.867}>
        <mesh geometry={nodes.Object_21.geometry} material={materials['material_0.005']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials['material_0.005']} />
      </group>
      <group position={[18.514, -6.674, 11.758]} rotation={[3.027, 1.449, -1.945]} scale={0.94}>
        <mesh geometry={nodes.Object_24.geometry} material={materials['material_0.006']} />
        <mesh geometry={nodes.Object_25.geometry} material={materials['material_0.006']} />
      </group>
      <group position={[16.852, 0, -8.877]} rotation={[2.625, 0.11, -0.919]} scale={0.917}>
        <mesh geometry={nodes.Object_27.geometry} material={materials['material_0.007']} />
        <mesh geometry={nodes.Object_28.geometry} material={materials['material_0.007']} />
      </group>
      <group position={[4.782, -4.211, 8.88]} rotation={[-2.862, -0.564, -0.488]}>
        <mesh geometry={nodes.Object_30.geometry} material={materials['material_0.008']} />
        <mesh geometry={nodes.Object_31.geometry} material={materials['material_0.008']} />
      </group>
      <group position={[-16.573, -8.216, 12.727]} rotation={[-0.687, -0.905, 0.997]} scale={1.202}>
        <mesh geometry={nodes.Object_33.geometry} material={materials['material_0.009']} />
        <mesh geometry={nodes.Object_34.geometry} material={materials['material_0.009']} />
      </group>
      <group position={[3.798, -9.713, -14.129]} rotation={[-0.644, 0.853, 2.646]} scale={1.026}>
        <mesh geometry={nodes.Object_36.geometry} material={materials['material_0.011']} />
        <mesh geometry={nodes.Object_37.geometry} material={materials['material_0.011']} />
      </group>
      <group position={[17.846, 2.161, 4.34]} rotation={[0.066, 0.297, -1.932]} scale={0.968}>
        <mesh geometry={nodes.Object_43.geometry} material={materials['material_0.014']} />
        <mesh geometry={nodes.Object_44.geometry} material={materials['material_0.014']} />
      </group>
      <group position={[-19.066, 8.654, 2.772]} rotation={[-2.834, -0.092, -1.019]} scale={1.184}>
        <mesh geometry={nodes.Object_46.geometry} material={materials['material_0.015']} />
        <mesh geometry={nodes.Object_47.geometry} material={materials['material_0.015']} />
      </group>
      <group position={[7.705, 3.864, 2.862]} rotation={[Math.PI / 2, -0.533, 0]} scale={1.1}>
        <mesh geometry={nodes.Object_49.geometry} material={materials['material_0.016']} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.material_1} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} position={[0.002, -0.01, -0.004]} rotation={[0.378, 1.566, -1.952]} scale={0.297} />
      <mesh geometry={nodes.Object_39.geometry} material={materials['material_0.012']} position={[12.479, 0, -15.979]} rotation={[2.189, 0.114, -1.52]} scale={0.753} />
      <mesh geometry={nodes.Object_41.geometry} material={materials['material_0.013']} position={[-14.938, 4.358, -11.024]} rotation={[1.517, -0.13, -0.156]} scale={1.246} />
      <mesh geometry={nodes.Object_52.geometry} material={materials['material_0.017']} position={[14.797, 7.941, -14.895]} rotation={[-2.91, 1.129, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
